### PR TITLE
Fix bug where run() does not return a statement object

### PR DESCRIPTION
**Pull request by theogravity**
Fixes https://github.com/kriasoft/node-sqlite/issues/7

### CODE REVIEW

**Comment by theogravity** [comment]
@koistya

**Comment by theogravity** [comment]
Will fix lint

**Comment by koistya** [comment]
Maybe it's better to wrap `this` into `new Statement(this, Promise)`?

**Comment by theogravity** [comment]
See https://github.com/kriasoft/node-sqlite/issues/7#issuecomment-233103340 as to why that will not work

**Comment by theogravity** [comment]
thanks!

**Comment by koistya** [comment]
@theogravity Just have published `v2.1.0`, thanks!

**Pull request merged**
