### PR TITLE
feat: update sqlite3 version supporting for node 11 and electron osx 3.0

### PR DESCRIPTION
**Pull request by yugasun**
Refer to https://github.com/mapbox/node-sqlite3/pull/1072

### CODE REVIEW

**Comment by frenzzy** [comment]
There are `^4.0.0` in package.json already which means you can use any version since 4.0.0 and up to 5.0.0, just update your local version. For example you can uninstall the package and install it again to use the latest version and update your package-lock.json file.

**Comment by yugasun** [comment]
@frenzzy But, you can find the sqlite3 version is locked in `yarn.lock` file, so this pr is still a need.

**Comment by frenzzy** [comment]
`yarn.lock` file is not included into npm package: https://unpkg.com/sqlite@3.0.0/
so, for users it does not matter what this file contains.

maybe add `yarn.lock` to `.gitignore` not to mislead anyone and keep repo clean...

**Comment by yugasun** [comment]
@frenzzy You are right, we can put `yarn.lock` into `.gitignore`, but I still suggest to update the `sqlite3` version and add `yarn.lock` into npm package for safety. Because when installing it, different `sqlite3` version may comes out in different environment.

**Comment by aashna208** [comment]
Hi, Is there any way to use this package with electron app?

**Comment by slorenzo** [comment]
@aashna208 Yes, I'm using this library with electron and seems to be working. Have you tried it?

**Comment by theogravity** [comment]
If you are still having problems, please try out the v4 beta (see the issues main for more info)

**Pull request closed without merging**
